#!/usr/bin/env bash
set -euo pipefail

export EXTRA=${EXTRA-$PWD/sysroot}
export PKG_CONFIG_PATH=$EXTRA/lib/pkgconfig:${PKG_CONFIG_PATH-}

if ! pkg-config "$@" ; then
  echo "--abort-the-build-because-some-libs-were-not-found"
  exit 1
fi
